# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.16.dev6+ge36f62e.d20230718'
__version_tuple__ = version_tuple = (0, 16, 'dev6', 'ge36f62e.d20230718')
