import recordlinkage.config as cf
from recordlinkage.config import (is_int, is_bool, is_text,
                                  is_instance_factory, is_one_of_factory,
                                  get_default_val, is_callable)

pairs_type_doc = """
: str
    Specify the format how record pairs are stored. By default, record
    pairs generated by the toolkit are returned in a
    pandas.MultiIndex object ('multiindex' option).

    Valid values: 'multiindex'
"""

with cf.config_prefix('indexing'):
    cf.register_option('pairs', 'multiindex', pairs_type_doc,
                       validator=is_one_of_factory(['multiindex']))
