name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Package recordlinkage
      run: |
        pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel sdist
    - name: Install recordlinkage
      run: |
        pip install networkx>=2
        pip install ./dist/recordlinkage-*.whl
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        # remove recordlinkage to prevent relative imports (use installed package)
        # this is like wrapping stuff in a src folder
        rm -r recordlinkage/
        pytest