name: Build HTML with Sphinx
on: [push, pull_request]
jobs:
  html-sphinx:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install recordlinkage and docs tools
      run: |
        sudo apt install pandoc
        python -m pip install .[docs]
    - name: Build HTML
      run: |
        python -m sphinx -W --keep-going --color docs/ _build/html/
