name: Docs Check
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install recordlinkage
      run: |
        pip install .[all]
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"